### ISSUE TITLE
Storybook Docs Support

### ISSUE THREAD

**Issue by davemooreuws** [InVisionApp/dsm-storybook-example-library#18]
Does the plugin support storybook docs from Storybook 5.2?

Link: https://github.com/storybookjs/storybook/tree/master/addons/docs

I am getting parse errors
DSM =>    Analyzing file stories/docs/building/creating.stories.mdx
DSM =>  × Failed to parse story source file "stories/docs/building/creating.stories.mdx"

**Comment by mortal94** [comment]
Hey @davemooreuws ,
`@invisionapp/dsm-storybook` currently don't parse `.mdx` files themself but allow to add them to a story file. you can see an example [here.](https://github.com/InVisionApp/dsm-storybook-example-library/blob/7a68b6f63cfdf604534b077ee529d63d9a81619c/react/storybook-v5/src/components/Button.stories.js#L37)
The error you received was caused because in your `.dsmrc` file you probably load `.mdx` files, which we do not support at the moment.
The solution should be to not include the `.mdx` extension in the property `storyPath` inside the `.dsmrc` file and import the `mdx` file to the story file as the example i shared above

**Comment by davemooreuws** [comment]
Hi @mortal94,

Thank you for your swift reply.
Are there any plans to support mdx in the initial parsing? My project does not use the typical story files and will now have to double the number of files, however this is a good workaround for now.

**Comment by mortal94** [comment]
Hey @davemooreuws ,
We have support for `mdx` in our backlog, but with no current estimate on availability.

**Comment by koga73** [comment]
@mortal94 I am also interested in support for `mdx` and noticed there is an mdx file in the example code. Is this a work in progress? Is there any sense of when mdx support will be released?

**Comment by jbernard-s4m** [comment]
> Hey @davemooreuws ,
> `@invisionapp/dsm-storybook` currently don't parse `.mdx` files themself but allow to add them to a story file. you can see an example [here.](https://github.com/InVisionApp/dsm-storybook-example-library/blob/7a68b6f63cfdf604534b077ee529d63d9a81619c/react/storybook-v5/src/components/Button.stories.js#L37)
> The error you received was caused because in your `.dsmrc` file you probably load `.mdx` files, which we do not support at the moment.
> The solution should be to not include the `.mdx` extension in the property `storyPath` inside the `.dsmrc` file and import the `mdx` file to the story file as the example i shared above

Is this possible in vue ? I mean can we link a `.mdx` to a story like in React ?
